// websites-data.js
const websites = [
  { title: "Google", url: "https://www.google.com", category: "search-engine" },
  { title: "Wikipedia", url: "https://www.wikipedia.org", category: "education-reference" },
  { title: "Sourceforge", url: "https://sourceforge.net/", category: "places" },
  { title: "Facebook", url: "https://www.facebook.com", category: "social-media" },
  { title: "Instagram", url: "https://www.instagram.com", category: "social-media" },
  { title: "YouTube", url: "https://www.youtube.com", category: "entertainment-streaming" },
  { title: "Bing", url: "https://www.bing.com", category: "search-engine" },
  { title: "Reddit", url: "https://www.reddit.com", category: "social-media" },
  { title: "X (formerly Twitter)", url: "https://www.x.com", category: "social-media" },
  { title: "ChatGPT", url: "https://www.chatgpt.com", category: "utilities" },
  { title: "Amazon", url: "https://www.amazon.com", category: "e-commerce" },
  { title: "Yahoo", url: "https://www.yahoo.com", category: "search-engine" },
  { title: "Weather.com", url: "https://www.weather.com", category: "utilities" },
  { title: "DuckDuckGo", url: "https://duckduckgo.com", category: "search-engine" },
  { title: "TikTok", url: "https://www.tiktok.com", category: "social-media" },
  { title: "Netflix", url: "https://www.netflix.com", category: "entertainment-streaming" },
  { title: "LinkedIn", url: "https://www.linkedin.com", category: "professional-networking" },
  { title: "Twitch", url: "https://www.twitch.tv", category: "entertainment-streaming" },
  { title: "Spotify", url: "https://www.spotify.com", category: "entertainment-streaming" },
  { title: "Discord", url: "https://discord.com", category: "social-media" },
  { title: "GitHub", url: "https://www.github.com", category: "utilities" },
  { title: "PayPal", url: "https://www.paypal.com", category: "e-commerce" },
  { title: "Canva", url: "https://www.canva.com", category: "utilities" },
  { title: "eBay", url: "https://www.ebay.com", category: "e-commerce" },
  { title: "NY Times", url: "https://www.nytimes.com", category: "news" },
];
